# Toml file - contains paramters for CFN
[deploy]
bucket = 'cfn-artifact'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddr.click'
EnvBackendUrl = 'https://api.cruddr.click'